#!/usr/bin/env python3
import json, pathlib, re, subprocess, sys
ROOT=pathlib.Path(__file__).resolve().parents[1]
S=ROOT/'sheets'; G=ROOT/'src'/'BrawlRounds'/'Generated'
def load(n): return json.loads((S/n).read_text(encoding='utf-8'))
def pascal(s): return ''.join(x[:1].upper()+x[1:] for x in re.split(r'[^A-Za-z0-9]+',s) if x)
def fl(v): return (f'{float(v):.4f}'.rstrip('0').rstrip('.')+'f')
def cs(s): return str(s).replace('\\','\\\\').replace('"','\\"')
subprocess.run([sys.executable,str(ROOT/'tools'/'preflight.py')],check=True)
for d in ['Weapons','Cards','Systems','Hooks']:
    p=G/d; p.mkdir(parents=True,exist_ok=True)
    for old in p.glob('*.g.cs'): old.unlink()
for w in load('weapons.json')['rows']:
    c=pascal(w['id'])+'Weapon'
    txt=("// <auto-generated />\nnamespace BrawlRounds.Generated.Weapons\n{\n"
         f"    internal sealed class {c} : WeaponDefinition\n    {{\n"
         f"        public {c}() : base(\"{cs(w['id'])}\", \"{cs(w['displayName'])}\", \"{cs(w['kind'])}\", {fl(w['damagePercent'])}, {fl(w['baseKnockback'])}, {fl(w['range'])}, {fl(w['cooldown'])}, {int(w['projectiles'])}, {fl(w['spread'])}, {fl(w['moveSpeedMultiplier'])}, {fl(w['pickupWeight'])}) {{ }}\n"
         "    }\n}\n")
    (G/'Weapons'/f'{c}.g.cs').write_text(txt,encoding='utf-8')
for card in load('cards.json')['rows']:
    c=pascal(card['id'])+'Card'
    rarity={'Common':'Common','Uncommon':'Uncommon','Rare':'Rare'}.get(card['rarity'],'Common')
    txt=f'''// <auto-generated />
using UnityEngine;
using UnboundLib.Cards;
using BrawlRounds.Runtime;

namespace BrawlRounds.Generated.Cards
{{
    internal sealed class {c} : CustomCard
    {{
        protected override string GetTitle() {{ return "{cs(card['displayName'])}"; }}
        protected override string GetDescription() {{ return "{cs(card['description'])}"; }}
        protected override GameObject GetCardArt() {{ return null; }}
        protected override CardInfo.Rarity GetRarity() {{ return CardInfo.Rarity.{rarity}; }}
        protected override CardInfoStat[] GetStats() {{ return new CardInfoStat[0]; }}
        protected override CardThemeColor.CardThemeColorType GetTheme() {{ return CardThemeColor.CardThemeColorType.TechWhite; }}
        public override string GetModName() {{ return "Brawl ROUNDS"; }}
        public override void SetupCard(CardInfo cardInfo, Gun gun, ApplyCardStats cardStats, CharacterStatModifiers stats, Block block)
        {{
            stats.movementSpeed *= {fl(card['movementSpeedMultiplier'])};
            stats.jump *= {fl(card['jumpMultiplier'])};
            stats.numberOfJumps += {int(card['extraJumps'])};
        }}
        public override void OnAddCard(Player player, Gun gun, GunAmmo ammo, CharacterData data, HealthHandler health, Gravity gravity, Block block, CharacterStatModifiers stats)
        {{
            CardRuntime.Add(player, new CardEffect {{ Id="{cs(card['id'])}", OutgoingKnockback={fl(card['outgoingKnockbackMultiplier'])}, IncomingKnockback={fl(card['incomingKnockbackMultiplier'])}, AttackCooldown={fl(card['attackCooldownMultiplier'])}, WeaponRange={fl(card['weaponRangeMultiplier'])} }});
        }}
        public override void OnRemoveCard(Player player, Gun gun, GunAmmo ammo, CharacterData data, HealthHandler health, Gravity gravity, Block block, CharacterStatModifiers stats)
        {{
            CardRuntime.Remove(player, "{cs(card['id'])}");
        }}
    }}
}}
'''
    (G/'Cards'/f'{c}.g.cs').write_text(txt,encoding='utf-8')
for row in load('systems.json')['rows']:
    c=pascal(row['id'])+'SystemRow'; deps=', '.join('"'+cs(x)+'"' for x in row['dependsOn'])
    txt=f'''// <auto-generated />
namespace BrawlRounds.Generated.Systems
{{
    internal sealed class {c} : SystemDefinition
    {{
        public {c}() : base("{cs(row['id'])}", "{cs(row['trigger'])}", "{cs(row['implementation'])}", new string[] {{ {deps} }}) {{ }}
    }}
}}
'''
    (G/'Systems'/f'{c}.g.cs').write_text(txt,encoding='utf-8')
for row in load('hooks.json')['rows']:
    c=pascal(row['id'])+'HookRow'
    txt=f'''// <auto-generated />
namespace BrawlRounds.Generated.Hooks
{{
    internal sealed class {c} : HookDefinition
    {{
        public {c}() : base("{cs(row['id'])}", "{cs(row['target'])}", "{cs(row['method'])}", "{cs(row['hookType'])}", "{cs(row['system'])}") {{ }}
    }}
}}
'''
    (G/'Hooks'/f'{c}.g.cs').write_text(txt,encoding='utf-8')
print('Generated',len(list(G.rglob('*.g.cs'))),'C# row artifacts.')
